_wandb:
    value:
        cli_version: 0.25.1
        e:
            0p5w4lbat1b824uo3icfz557kp189rzk:
                args:
                    - --wandb_key
                    - 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
                    - --hf_token
                    - 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
                    - --hf_repo
                    - Jaishankar02/vit-cifar100-lora-best
                codePath: q1_optuna.py
                codePathLocal: q1_optuna.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "75125227520"
                        used: "25108869120"
                email: m25csa014@iitj.ac.in
                executable: /csehome/m25csa014/Dlops_ass5/myconda/envs/q1_env/bin/python
                gpu: NVIDIA A30
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "25769803776"
                      name: NVIDIA A30
                      uuid: GPU-181f39d6-10d1-8586-687e-dbd6bed41a1e
                host: cn02
                memory:
                    total: "269827448832"
                os: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
                program: /csehome/m25csa014/Dlops_ass5/q1_optuna.py
                python: CPython 3.10.20
                root: /csehome/m25csa014/Dlops_ass5
                slurm:
                    cluster_name: csedpu
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: root
                    job_cpus_per_node: "4"
                    job_end_time: "1775427656"
                    job_gid: "2004"
                    job_gpus: "1"
                    job_id: "32097"
                    job_name: optuna_search
                    job_nodelist: cn02
                    job_num_nodes: "1"
                    job_partition: mtech
                    job_qos: normal
                    job_start_time: "1775298056"
                    job_uid: "2477"
                    job_user: m25csa014
                    jobid: "32097"
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: cn02
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /csehome/m25csa014/Dlops_ass5
                    submit_host: login.cse.iitj.ac.in
                    task_pid: "748773"
                    tasks_per_node: "1"
                    topology_addr: cn02
                    topology_addr_pattern: node
                    tres_per_task: cpu:4
                startedAt: "2026-04-04T10:21:45.705865Z"
                writerId: 0p5w4lbat1b824uo3icfz557kp189rzk
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 11
                - 35
                - 41
                - 49
                - 63
                - 71
                - 98
            "2":
                - 1
                - 11
                - 35
                - 41
                - 49
                - 63
                - 71
                - 98
            "3":
                - 2
                - 13
            "4": 3.10.20
            "5": 0.25.1
            "6": 4.40.0
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
